apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-spring-on-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hungtrannhatt/INT3236E1_week8.git
    path: hello-spring-k8s/k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true