apiVersion: v1
kind: Service
metadata:
  name: web-login
  labels:
    app: web-login
spec:
  type: ClusterIP
  selector:
    app: web-login
  ports:
    - name: http
      port: 80
      targetPort: 8080
